spring:
  datasource:
    username: 'app'
    password: '123456'
    url: 'jdbc:postgresql://1349291-cu57808.tw1.ru:5432/smktdb'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: '1349291-cu57808.tw1.ru:29092'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: 'samokatim-service'
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: 'http://1349291-cu57808.tw1.ru:8081'
      specific.avro.reader: true
  cloud:
    kubernetes:
      discovery:
        all-namespaces: false

management:
  endpoint:
    health:
      probes:
        enabled: true

integration:
  dadata:
    base-url: 'https://suggestions.dadata.ru'
    token: '85e144d751ad4c1df93f49cf09535c23110e34c0'

auth:
  secret: 'kwjqjifhijdwsghijkosdfjgoksdfjihjdfoihjdfo5345ihjdfijhiodfjhoikfdjhkojdfkohjfdkjhkofdjhkohdfgikhjokdfjhikfdjihjo'